# Generated by Django 4.2.30 on 2026-07-21 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_registrations', models.IntegerField(default=0)),
                ('active_candidates', models.IntegerField(default=0)),
                ('active_recruiters', models.IntegerField(default=0)),
                ('total_resumes', models.IntegerField(default=0)),
                ('total_jobs', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('total_ai_requests', models.IntegerField(default=0)),
                ('avg_ats_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('resume_parsing', 'Resume Parsing'), ('ats_scoring', 'ATS Scoring'), ('cover_letter', 'Cover Letter Generation'), ('interview_questions', 'Interview Question Generation'), ('job_matching', 'Job Matching'), ('skill_gap', 'Skill Gap Analysis'), ('resume_improvement', 'Resume Improvement'), ('candidate_ranking', 'Candidate Ranking')], max_length=30)),
                ('tokens_used', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
