# Generated by Django 4.2.30 on 2026-07-21 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Resume', max_length=200)),
                ('file', models.FileField(upload_to='resumes/')),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('analyzed', 'Analyzed'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming Language'), ('framework', 'Framework'), ('database', 'Database'), ('tool', 'Tool'), ('cloud', 'Cloud Platform'), ('soft', 'Soft Skill'), ('other', 'Other')], default='other', max_length=20)),
                ('normalized_name', models.CharField(max_length=100, unique=True)),
                ('popularity_score', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-popularity_score'],
            },
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=200)),
                ('current_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('learning_roadmap', models.JSONField(default=list)),
                ('match_percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('original_text', models.TextField()),
                ('improved_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('expected_answer', models.TextField(blank=True)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('category', models.CharField(default='technical', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('raw_sections', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tone', models.CharField(default='professional', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ATSScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0)),
                ('formatting_score', models.FloatField(default=0)),
                ('skills_match_score', models.FloatField(default=0)),
                ('experience_score', models.FloatField(default=0)),
                ('education_score', models.FloatField(default=0)),
                ('keywords_score', models.FloatField(default=0)),
                ('projects_score', models.FloatField(default=0)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('target_job_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_score', to='resumes.resume')),
            ],
        ),
    ]
