# Generated by Django 4.2.30 on 2026-07-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiterprofile",
            name="company_logo",
            field=models.FileField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.FileField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
